.PHONY: clean All

All:
	@echo "----------Building project:[ FlyRobot_Main - Debug ]----------"
	@$(MAKE) -f  "FlyRobot_Main.mk"
clean:
	@echo "----------Cleaning project:[ FlyRobot_Main - Debug ]----------"
	@$(MAKE) -f  "FlyRobot_Main.mk" clean
